version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - "pgadmindata:/var/lib/pgadmin"

volumes:
  pgadmindata:
